export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNDLOAD_PRODUCTS = 'START_DOWNDLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCESS = 'DOWNLOAD_PRODUCTS_SUCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_SUCESS = 'PRODUCT_DELETE_SUCESS';
export const  PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';
